### PR TITLE
Eliminate Pattern.compile, match, and String concatenations in Ipv6Ad…

### PR DESCRIPTION
**Pull request by omuravskiy**
…dress.parse

### CODE REVIEW

**Comment by constpetrov** [comment]
Could you also remove import of Pattern? It is not needed anymore.

**Comment by omuravskiy** [comment]
> Could you also remove import of Pattern? It is not needed anymore.

It is still used to check that the overall syntax of IPv6 address is correct.
I'm not sure just removing this check is safe. But factoring out pattern match by something simpler would be a good thing to do. Any volunteers?

**Comment by omuravskiy** [comment]
Hey guys, I'd really like to merge and release this, as the exceptions from trying to parse IPv6 addresses as IPv4 first are killing performance.

**Comment by lolepezy** [comment]
Oh sorry, I thought I pressed the button, but apparently I just said "uhu" to myself. Done.

**Pull request merged**
